---
# tasks file for eap-7-deploy-application
  - name: Check for correct OS family & min version
    assert:
      that: "ansible_os_family == '{{ os_family_supported }}'"
      that: "ansible_distribution_version >= '{{ os_min_supported_version }}'"
    tags:
     - oscheck

  - name: Deploy application
    shell:
      cmd: '{{jboss_client}} --user={{jboss_admin}} --password={{jboss_admin_password}} --connect --command="deploy {{jboss_application}}"'
    register: output

  - name: Debug Deployment
    debug: var=output

