---
# tasks file for eap-7-start
  - name: Check for correct OS family & min version
    assert:
      that: "ansible_os_family == '{{ os_family_supported }}'"
      that: "ansible_distribution_version >= '{{ os_min_supported_version }}'"
    tags:
     - oscheck

  - name: Start & enable JBoss Systemd service
    shell:
      cmd: "'{{ jboss_add_user }}' -u '{{ jboss_user }}' -p '{{ jboss_user_password }}' -g 'admin'"
    become: true
    become_method: sudo
    register: output

  - name: Debug Deployment
    debug: var=output

    become: true
    become_method: sudo
