---
- name: Install Java 1.8 and some basic dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python
